server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/java-projects
    username: postgres
    password: root-password-123
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: test_task_db

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: test_task_db

  liquibase:
    enabled: true
    default-schema: test_task_db
    change-log: classpath:db/changelog/db.changelog-master.yaml
  cache:
    type: caffeine
    expire-after-access: 600 000
    maximum-size: 1000

security:
  jwt:
    secret: a-string-secret-at-least-256-bits-long
    access-expiration: 86400000
    refresh-expiration: 2629800000

logging:
  level:
    ru.blaskowitz.java.test.task.aspect: info